---
title: "Temperature_Experiment"
author: "E. Alejandro Pardo"
date: "2025-10-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
library(ggplot2)
library(tidyverse)
library(pracma)
library(rstatix)
library(gridExtra)
library(readxl)
library(ggh4x)
library(ggforce)
library(patchwork) 
library(signal)
library(dplyr)
library(writexl)
library(RHRV)
library(readr)

folder_path <- "C:/Users/jandr/OneDrive - Universidad del rosario/Temperature_Pressure_HRV/Data/data_extraction/Cold_experiment"
files <-  list.files(path = folder_path, pattern = "*Ven_Edited", full.names = TRUE)
print(files)
read_and_label <- function(file) {
  df <- read.csv(file)
  df$source_file <- basename(file)  # Add filename column
  return(df)
}

data_list <- lapply(files, read_and_label)

Data_complete_temperature_cold <- bind_rows(data_list)  %>% 
   mutate(Treatment = str_extract(source_file,  "(?<=\\d_)[^_]+")) %>% 
  mutate(Snail = str_extract(source_file,  "\\d+")) %>% rename("Frame" = X) %>% mutate(Time = Frame*(1/30))

View(Data_complete_temperature_cold)

View(Data_complete_temperature)
Data_complete_temperature$Mean.Ventricle.

 p <- Data_complete_temperature %>%
    dplyr::filter(Snail == 1) %>%
    ggplot(aes(x = Frame, y = Mean.Ventricle., color = Treatment, group = Treatment)) +
    geom_line(size = 0.8, alpha = 0.8) +
    geom_point(size = 0.8, alpha = 0.7) +
    theme_minimal(base_size = 11) + facet_wrap(~Treatment, ncol = 1)+
    labs(
      x = "Frame",
      y = "Mean intensity (a.u.)"
    ) + theme_bw() +theme(
    strip.text = element_blank(),  # ← elimina el texto de las facetas
    strip.background = element_blank(),  # ← elimina el fondo gris
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "bottom"
  )
  
  print(p)  

  
write_xlsx(Data_complete_temperature, "Data_complete_temperature.xlsx")
Data_complete_temperature$Time


```


```{r}
#completado
folder_path <- "C:/Users/jandr/OneDrive - Universidad del rosario/Temperature_Pressure_HRV/Data/data_extraction/Cold_experiment"
Treatments <- c("1°C","8°C","15°C","WATCOLD", "ENVCOLD")
#Descartar 4, 19, 7, 26
#al azar descartado: 10
ids_disponibles <- c(1, 2, 5, 6, 8, 9,11, 12, 13,14,15,17,18, 20,21, 22,23,24, 25, 27, 28, 29, 30, 31)
todos_los_resultados_movimiento <- list()  # Create an empty list to store results
for (id in ids_disponibles) {
filename <- file.path(folder_path, paste0(id, "_ENVCOLD_Ven_Edited.csv"))
    cat("Buscando:", filename, "\n")
  if (!file.exists(filename)) {
    cat("File not found for ID", id, "\n")
    next
  }
  
  data <- read_csv(filename)

duracion_seg <- 60  # o el valor real
data_long <- data %>%   
  select(contains("Mean")) %>% 
  mutate(t = seq(0, duracion_seg, length.out = n())) %>% 
  pivot_longer(-t, names_to = "Mean", values_to = "value")
  results <- data_long %>% arrange(t) %>% 
    mutate(smoothed = sgolayfilt(value, p = 5, n = 25), trend = predict(loess(smoothed ~ t, span = 0.08), newdata = data.frame(t = t))) 

  derivative <- c(NA, diff(results$smoothed))  # Smoothing and derivative
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from negative to positive (local minima)
  valley_indices <- which(significant_changes == 2)
  valley_values <- results$smoothed[valley_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))
  threshold <- 1 * trend
  valid_valleys <- valley_indices[valley_values < threshold[valley_indices]]
  min_dist <- 18
  values <- results$smoothed[valid_valleys]
  filtered_valleys <- c()

  if (length(valid_valleys) == 1) {
    filtered_valleys <- valid_valleys
  } else if (length(valid_valleys) > 1) {
    current_group <- c(valid_valleys[1])
    filtered_valleys <- c()
    
    for (i in 2:length(valid_valleys)) {
      if ((valid_valleys[i] - valid_valleys[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_valleys[i])
      } else {
        min_valley <- current_group[which.min(results$smoothed[current_group])]
        filtered_valleys <- c(filtered_valleys, min_valley)
        current_group <- c(valid_valleys[i])
      }
    }
    
    if (length(current_group) > 0) {
      min_valley <- current_group[which.min(results$smoothed[current_group])]
      filtered_valleys <- c(filtered_valleys, min_valley)
    }
  }

  local_valley_threshold <- trend[filtered_valleys]
  filtered_valley_values <- results$smoothed[filtered_valleys]
  valley_trend_filter <- filtered_valley_values < local_valley_threshold
  filtered_valleys <- filtered_valleys[valley_trend_filter]

  if (length(filtered_valleys) > 0) {
    final_valleys <- tibble(
      time = results$t[filtered_valleys],
      value = results$smoothed[filtered_valleys]
    )
  } else {
    final_valleys <- NULL
  }

  derivative <- c(NA, diff(results$smoothed))
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from positive to negative (local maxima)
  peak_indices <- which(significant_changes == -2)
  peak_values <- results$smoothed[peak_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))

  threshold <- 1.01 * trend
  local_threshold <- threshold[peak_indices]

  valid_peaks <- peak_indices[peak_values > local_threshold]
  min_dist <- 13
  values <- results$smoothed[valid_peaks]

  filtered_peaks <- c()

  if (length(valid_peaks) == 1) {
    filtered_peaks <- valid_peaks
  } else if (length(valid_peaks) > 1) {
    current_group <- c(valid_peaks[1])
    filtered_peaks <- c()
    
    for (i in 2:length(valid_peaks)) {
      if ((valid_peaks[i] - valid_peaks[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_peaks[i])
      } else {
        max_peak <- current_group[which.max(results$smoothed[current_group])]
        filtered_peaks <- c(filtered_peaks, max_peak)
        current_group <- c(valid_peaks[i])
      }
    }
    
    if (length(current_group) > 0) {
      max_peak <- current_group[which.max(results$smoothed[current_group])]
      filtered_peaks <- c(filtered_peaks, max_peak)
    }
  }

  local_threshold_filtered <- trend[filtered_peaks]
  filtered_values <- results$smoothed[filtered_peaks]
  trend_filter <- filtered_values > local_threshold_filtered
  filtered_peaks <- filtered_peaks[trend_filter]

  if (length(filtered_peaks) > 0) {
    final_peaks <- tibble(
      time = results$t[filtered_peaks],
      value = results$smoothed[filtered_peaks]
    )
  } else {
    final_peaks <- NULL
  }

  data_smoothed <- bind_rows(results)

  cat("Processed ID", id, "\n")


  plot_individual <- ggplot(data_smoothed, aes(x = t)) +
    geom_line(aes(y = value, color = "Raw signal"), size = 0.8) +
    geom_line(aes(y = smoothed, color = "Smoothed signal"), size = 0.9) +
    geom_line(aes(y = trend, color = "Trend", linetype = "Trend"), size = 1) +
    geom_point(data = final_valleys, aes(x = time, y = value, color = "Valleys", shape = "Valleys"), size = 2) +
    geom_point(data = final_peaks, aes(x = time, y = value, color = "Peaks", shape = "Peaks"), size = 2) +

    labs(title = paste("Signals and detected peaks - ID", id),
         x = "Time (s)", y = "Intensity", color = "", linetype = "", shape = "") +

    scale_color_manual(values = c(
      "Raw signal" = "gray70",
      "Smoothed signal" = "blue",
      "Trend" = "green",
      "Valleys" = "orange",
      "Peaks" = "red"
    )) +
    scale_linetype_manual(values = c("Trend" = "dashed")) +
    scale_shape_manual(values = c("Valleys" = 16, "Peaks" = 16)) +

    theme_minimal(base_size = 14) +
    theme(
      plot.background = element_rect(fill = "white", color = NA),
      panel.background = element_rect(fill = "white", color = NA),
      strip.background = element_rect(fill = "white", color = NA),
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "black"),
      axis.title = element_text(size = 14, color = "black"),
      axis.text = element_text(size = 12, color = "black"),
      strip.text = element_text(color = "black"),
      legend.text = element_text(color = "black")
    )

  ggsave(filename = file.path(folder_path, "Graphs", paste0("Graph_ENVCOLD", id, ".png")),
         plot = plot_individual, width = 12, height = 8, dpi = 300)

  todos_los_resultados_movimiento[[as.character(id)]] <- list(
    data_suavizado = data_smoothed %>% mutate(ID = id),
    valles_finales = final_valleys %>% mutate(ID = id),
    picos_finales = final_peaks %>% mutate(ID = id)
  )
  }

data_suavizado_all <- map_dfr(todos_los_resultados_movimiento, "data_suavizado")
all_ENVCOLD_valleys <- map_dfr(todos_los_resultados_movimiento, "valles_finales")
picos_ENVCOLD_rep <- map_dfr(todos_los_resultados_movimiento, "picos_finales")


ids_disponibles <- 3
todos_los_resultados_movimiento <- list()  # Create an empty list to store results
for (id in ids_disponibles) {
filename <- file.path(folder_path, paste0(id, "_ENVCOLD_Ven_Edited.csv"))
    cat("Buscando:", filename, "\n")
  if (!file.exists(filename)) {
    cat("File not found for ID", id, "\n")
    next
  }
  
  data <- read_csv(filename)

duracion_seg <- 60  # o el valor real
data_long <- data %>%   
  select(contains("Mean")) %>% 
  mutate(t = seq(0, duracion_seg, length.out = n())) %>% 
  pivot_longer(-t, names_to = "Mean", values_to = "value")
  results <- data_long %>% arrange(t) %>% 
    mutate(smoothed = sgolayfilt(value, p = 5, n = 25), trend = predict(loess(smoothed ~ t, span = 0.08), newdata = data.frame(t = t))) 

  derivative <- c(NA, diff(results$smoothed))  # Smoothing and derivative
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from negative to positive (local minima)
  valley_indices <- which(significant_changes == 2)
  valley_values <- results$smoothed[valley_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))
  threshold <- 0.995 * trend
  valid_valleys <- valley_indices[valley_values < threshold[valley_indices]]
  min_dist <- 15
  values <- results$smoothed[valid_valleys]
  filtered_valleys <- c()

  if (length(valid_valleys) == 1) {
    filtered_valleys <- valid_valleys
  } else if (length(valid_valleys) > 1) {
    current_group <- c(valid_valleys[1])
    filtered_valleys <- c()
    
    for (i in 2:length(valid_valleys)) {
      if ((valid_valleys[i] - valid_valleys[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_valleys[i])
      } else {
        min_valley <- current_group[which.min(results$smoothed[current_group])]
        filtered_valleys <- c(filtered_valleys, min_valley)
        current_group <- c(valid_valleys[i])
      }
    }
    
    if (length(current_group) > 0) {
      min_valley <- current_group[which.min(results$smoothed[current_group])]
      filtered_valleys <- c(filtered_valleys, min_valley)
    }
  }

  local_valley_threshold <- trend[filtered_valleys]
  filtered_valley_values <- results$smoothed[filtered_valleys]
  valley_trend_filter <- filtered_valley_values < local_valley_threshold
  filtered_valleys <- filtered_valleys[valley_trend_filter]

  if (length(filtered_valleys) > 0) {
    final_valleys <- tibble(
      time = results$t[filtered_valleys],
      value = results$smoothed[filtered_valleys]
    )
  } else {
    final_valleys <- NULL
  }

  derivative <- c(NA, diff(results$smoothed))
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from positive to negative (local maxima)
  peak_indices <- which(significant_changes == -2)
  peak_values <- results$smoothed[peak_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))

  threshold <- 1.01 * trend
  local_threshold <- threshold[peak_indices]

  valid_peaks <- peak_indices[peak_values > local_threshold]
  min_dist <- 13
  values <- results$smoothed[valid_peaks]

  filtered_peaks <- c()

  if (length(valid_peaks) == 1) {
    filtered_peaks <- valid_peaks
  } else if (length(valid_peaks) > 1) {
    current_group <- c(valid_peaks[1])
    filtered_peaks <- c()
    
    for (i in 2:length(valid_peaks)) {
      if ((valid_peaks[i] - valid_peaks[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_peaks[i])
      } else {
        max_peak <- current_group[which.max(results$smoothed[current_group])]
        filtered_peaks <- c(filtered_peaks, max_peak)
        current_group <- c(valid_peaks[i])
      }
    }
    
    if (length(current_group) > 0) {
      max_peak <- current_group[which.max(results$smoothed[current_group])]
      filtered_peaks <- c(filtered_peaks, max_peak)
    }
  }

  local_threshold_filtered <- trend[filtered_peaks]
  filtered_values <- results$smoothed[filtered_peaks]
  trend_filter <- filtered_values > local_threshold_filtered
  filtered_peaks <- filtered_peaks[trend_filter]

  if (length(filtered_peaks) > 0) {
    final_peaks <- tibble(
      time = results$t[filtered_peaks],
      value = results$smoothed[filtered_peaks]
    )
  } else {
    final_peaks <- NULL
  }

  data_smoothed <- bind_rows(results)

  cat("Processed ID", id, "\n")


  plot_individual <- ggplot(data_smoothed, aes(x = t)) +
    geom_line(aes(y = value, color = "Raw signal"), size = 0.8) +
    geom_line(aes(y = smoothed, color = "Smoothed signal"), size = 0.9) +
    geom_line(aes(y = trend, color = "Trend", linetype = "Trend"), size = 1) +
    geom_point(data = final_valleys, aes(x = time, y = value, color = "Valleys", shape = "Valleys"), size = 2) +
    geom_point(data = final_peaks, aes(x = time, y = value, color = "Peaks", shape = "Peaks"), size = 2) +

    labs(title = paste("Signals and detected peaks - ID", id),
         x = "Time (s)", y = "Intensity", color = "", linetype = "", shape = "") +

    scale_color_manual(values = c(
      "Raw signal" = "gray70",
      "Smoothed signal" = "blue",
      "Trend" = "green",
      "Valleys" = "orange",
      "Peaks" = "red"
    )) +
    scale_linetype_manual(values = c("Trend" = "dashed")) +
    scale_shape_manual(values = c("Valleys" = 16, "Peaks" = 16)) +

    theme_minimal(base_size = 14) +
    theme(
      plot.background = element_rect(fill = "white", color = NA),
      panel.background = element_rect(fill = "white", color = NA),
      strip.background = element_rect(fill = "white", color = NA),
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "black"),
      axis.title = element_text(size = 14, color = "black"),
      axis.text = element_text(size = 12, color = "black"),
      strip.text = element_text(color = "black"),
      legend.text = element_text(color = "black")
    )

  ggsave(filename = file.path(folder_path, "Graphs", paste0("Graph_ENVCOLD", id, ".png")),
         plot = plot_individual, width = 12, height = 8, dpi = 300)

  todos_los_resultados_movimiento[[as.character(id)]] <- list(
    data_suavizado = data_smoothed %>% mutate(ID = id),
    valles_finales = final_valleys %>% mutate(ID = id),
    picos_finales = final_peaks %>% mutate(ID = id)
  )
  }

data_suavizado_all <- map_dfr(todos_los_resultados_movimiento, "data_suavizado")
a_3_ENVCOLD_valleys <- map_dfr(todos_los_resultados_movimiento, "valles_finales")
picos_ENVCOLD_rep <- map_dfr(todos_los_resultados_movimiento, "picos_finales")

# Merge all results
all_ENVCOLD_valleys <- all_ENVCOLD_valleys %>% bind_rows(a_3_ENVCOLD_valleys)
view(all_ENVCOLD_valleys)

```




```{r}
#Completado
folder_path <- "C:/Users/jandr/OneDrive - Universidad del rosario/Temperature_Pressure_HRV/Data/data_extraction/Cold_experiment"
Treatments <- c("1°C","8°C","15°C","WATCOLD", "ENVCOLD")
#artefacto en 1 y 9
#skipped beat en 2 y 3 y 26
#Descartar 19, 20, 21, 23
#al azar descartar: 24, 26
ids_disponibles <- c(4,5, 6, 7, 8,10, 11, 12, 13,14,15,16,17,18, 22, 25, 27, 28, 29, 30, 31)
todos_los_resultados_movimiento <- list()  # Create an empty list to store results
for (id in ids_disponibles) {
filename <- file.path(folder_path, paste0(id, "_WATCOLD_Ven_Edited.csv"))
    cat("Buscando:", filename, "\n")
  if (!file.exists(filename)) {
    cat("File not found for ID", id, "\n")
    next
  }
  
  data <- read_csv(filename)

duracion_seg <- 60  # o el valor real
data_long <- data %>%   
  select(contains("Mean")) %>% 
  mutate(t = seq(0, duracion_seg, length.out = n())) %>% 
  pivot_longer(-t, names_to = "Mean", values_to = "value")

  results <- data_long %>% arrange(t) %>% 
    mutate(smoothed = sgolayfilt(value, p = 5, n = 25), trend = predict(loess(smoothed ~ t, span = 0.08), newdata = data.frame(t = t))) 

  derivative <- c(NA, diff(results$smoothed))  # Smoothing and derivative
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from negative to positive (local minima)
  valley_indices <- which(significant_changes == 2)
  valley_values <- results$smoothed[valley_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))
  threshold <- 1 * trend
  valid_valleys <- valley_indices[valley_values < threshold[valley_indices]]
  min_dist <- 17
  values <- results$smoothed[valid_valleys]
  filtered_valleys <- c()

  if (length(valid_valleys) == 1) {
    filtered_valleys <- valid_valleys
  } else if (length(valid_valleys) > 1) {
    current_group <- c(valid_valleys[1])
    filtered_valleys <- c()
    
    for (i in 2:length(valid_valleys)) {
      if ((valid_valleys[i] - valid_valleys[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_valleys[i])
      } else {
        min_valley <- current_group[which.min(results$smoothed[current_group])]
        filtered_valleys <- c(filtered_valleys, min_valley)
        current_group <- c(valid_valleys[i])
      }
    }
    
    if (length(current_group) > 0) {
      min_valley <- current_group[which.min(results$smoothed[current_group])]
      filtered_valleys <- c(filtered_valleys, min_valley)
    }
  }

  local_valley_threshold <- trend[filtered_valleys]
  filtered_valley_values <- results$smoothed[filtered_valleys]
  valley_trend_filter <- filtered_valley_values < local_valley_threshold
  filtered_valleys <- filtered_valleys[valley_trend_filter]

  if (length(filtered_valleys) > 0) {
    final_valleys <- tibble(
      time = results$t[filtered_valleys],
      value = results$smoothed[filtered_valleys]
    )
  } else {
    final_valleys <- NULL
  }

  derivative <- c(NA, diff(results$smoothed))
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from positive to negative (local maxima)
  peak_indices <- which(significant_changes == -2)
  peak_values <- results$smoothed[peak_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))

  threshold <- 1.01 * trend
  local_threshold <- threshold[peak_indices]

  valid_peaks <- peak_indices[peak_values > local_threshold]
  min_dist <- 18
  values <- results$smoothed[valid_peaks]

  filtered_peaks <- c()

  if (length(valid_peaks) == 1) {
    filtered_peaks <- valid_peaks
  } else if (length(valid_peaks) > 1) {
    current_group <- c(valid_peaks[1])
    filtered_peaks <- c()
    
    for (i in 2:length(valid_peaks)) {
      if ((valid_peaks[i] - valid_peaks[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_peaks[i])
      } else {
        max_peak <- current_group[which.max(results$smoothed[current_group])]
        filtered_peaks <- c(filtered_peaks, max_peak)
        current_group <- c(valid_peaks[i])
      }
    }
    
    if (length(current_group) > 0) {
      max_peak <- current_group[which.max(results$smoothed[current_group])]
      filtered_peaks <- c(filtered_peaks, max_peak)
    }
  }

  local_threshold_filtered <- trend[filtered_peaks]
  filtered_values <- results$smoothed[filtered_peaks]
  trend_filter <- filtered_values > local_threshold_filtered
  filtered_peaks <- filtered_peaks[trend_filter]

  if (length(filtered_peaks) > 0) {
    final_peaks <- tibble(
      time = results$t[filtered_peaks],
      value = results$smoothed[filtered_peaks]
    )
  } else {
    final_peaks <- NULL
  }

  data_smoothed <- bind_rows(results)

  cat("Processed ID", id, "\n")


  plot_individual <- ggplot(data_smoothed, aes(x = t)) +
    geom_line(aes(y = value, color = "Raw signal"), size = 0.8) +
    geom_line(aes(y = smoothed, color = "Smoothed signal"), size = 0.9) +
    geom_line(aes(y = trend, color = "Trend", linetype = "Trend"), size = 1) +
    geom_point(data = final_valleys, aes(x = time, y = value, color = "Valleys", shape = "Valleys"), size = 2) +
    geom_point(data = final_peaks, aes(x = time, y = value, color = "Peaks", shape = "Peaks"), size = 2) +

    labs(title = paste("Signals and detected peaks - ID", id),
         x = "Time (s)", y = "Intensity", color = "", linetype = "", shape = "") +

    scale_color_manual(values = c(
      "Raw signal" = "gray70",
      "Smoothed signal" = "blue",
      "Trend" = "green",
      "Valleys" = "orange",
      "Peaks" = "red"
    )) +
    scale_linetype_manual(values = c("Trend" = "dashed")) +
    scale_shape_manual(values = c("Valleys" = 16, "Peaks" = 16)) +

    theme_minimal(base_size = 14) +
    theme(
      plot.background = element_rect(fill = "white", color = NA),
      panel.background = element_rect(fill = "white", color = NA),
      strip.background = element_rect(fill = "white", color = NA),
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "black"),
      axis.title = element_text(size = 14, color = "black"),
      axis.text = element_text(size = 12, color = "black"),
      strip.text = element_text(color = "black"),
      legend.text = element_text(color = "black")
    )

  ggsave(filename = file.path(folder_path, "Graphs", paste0("Graph__WATCOLD", id, ".png")),
         plot = plot_individual, width = 12, height = 8, dpi = 300)

  todos_los_resultados_movimiento[[as.character(id)]] <- list(
    data_suavizado = data_smoothed %>% mutate(ID = id),
    valles_finales = final_valleys %>% mutate(ID = id),
    picos_finales = final_peaks %>% mutate(ID = id)
  )
  }

data_suavizado_all <- map_dfr(todos_los_resultados_movimiento, "data_suavizado")
all_WATCOLD_valleys <- map_dfr(todos_los_resultados_movimiento, "valles_finales")
picos_WATCOLD_rep <- map_dfr(todos_los_resultados_movimiento, "picos_finales")



ids_disponibles <- c(1,9)
todos_los_resultados_movimiento <- list()  # Create an empty list to store results
for (id in ids_disponibles) {
filename <- file.path(folder_path, paste0(id, "_WATCOLD_Ven_Edited.csv"))
    cat("Buscando:", filename, "\n")
  if (!file.exists(filename)) {
    cat("File not found for ID", id, "\n")
    next
  }
  
  data <- read_csv(filename)

duracion_seg <- 60  # o el valor real
data_long <- data %>%   
  select(contains("Mean")) %>% 
  mutate(t = seq(0, duracion_seg, length.out = n())) %>% 
  pivot_longer(-t, names_to = "Mean", values_to = "value")

  results <- data_long %>% arrange(t) %>% 
    mutate(smoothed = sgolayfilt(value, p = 5, n = 25), trend = predict(loess(smoothed ~ t, span = 0.08), newdata = data.frame(t = t))) 

  derivative <- c(NA, diff(results$smoothed))  # Smoothing and derivative
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from negative to positive (local minima)
  valley_indices <- which(significant_changes == 2)
  valley_values <- results$smoothed[valley_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))
  threshold <- 0.99 * trend
  valid_valleys <- valley_indices[valley_values < threshold[valley_indices]]
  min_dist <- 17
  values <- results$smoothed[valid_valleys]
  filtered_valleys <- c()

  if (length(valid_valleys) == 1) {
    filtered_valleys <- valid_valleys
  } else if (length(valid_valleys) > 1) {
    current_group <- c(valid_valleys[1])
    filtered_valleys <- c()
    
    for (i in 2:length(valid_valleys)) {
      if ((valid_valleys[i] - valid_valleys[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_valleys[i])
      } else {
        min_valley <- current_group[which.min(results$smoothed[current_group])]
        filtered_valleys <- c(filtered_valleys, min_valley)
        current_group <- c(valid_valleys[i])
      }
    }
    
    if (length(current_group) > 0) {
      min_valley <- current_group[which.min(results$smoothed[current_group])]
      filtered_valleys <- c(filtered_valleys, min_valley)
    }
  }

  local_valley_threshold <- trend[filtered_valleys]
  filtered_valley_values <- results$smoothed[filtered_valleys]
  valley_trend_filter <- filtered_valley_values < local_valley_threshold
  filtered_valleys <- filtered_valleys[valley_trend_filter]

  if (length(filtered_valleys) > 0) {
    final_valleys <- tibble(
      time = results$t[filtered_valleys],
      value = results$smoothed[filtered_valleys]
    )
  } else {
    final_valleys <- NULL
  }

  derivative <- c(NA, diff(results$smoothed))
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from positive to negative (local maxima)
  peak_indices <- which(significant_changes == -2)
  peak_values <- results$smoothed[peak_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))

  threshold <- 1.01 * trend
  local_threshold <- threshold[peak_indices]

  valid_peaks <- peak_indices[peak_values > local_threshold]
  min_dist <- 18
  values <- results$smoothed[valid_peaks]

  filtered_peaks <- c()

  if (length(valid_peaks) == 1) {
    filtered_peaks <- valid_peaks
  } else if (length(valid_peaks) > 1) {
    current_group <- c(valid_peaks[1])
    filtered_peaks <- c()
    
    for (i in 2:length(valid_peaks)) {
      if ((valid_peaks[i] - valid_peaks[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_peaks[i])
      } else {
        max_peak <- current_group[which.max(results$smoothed[current_group])]
        filtered_peaks <- c(filtered_peaks, max_peak)
        current_group <- c(valid_peaks[i])
      }
    }
    
    if (length(current_group) > 0) {
      max_peak <- current_group[which.max(results$smoothed[current_group])]
      filtered_peaks <- c(filtered_peaks, max_peak)
    }
  }

  local_threshold_filtered <- trend[filtered_peaks]
  filtered_values <- results$smoothed[filtered_peaks]
  trend_filter <- filtered_values > local_threshold_filtered
  filtered_peaks <- filtered_peaks[trend_filter]

  if (length(filtered_peaks) > 0) {
    final_peaks <- tibble(
      time = results$t[filtered_peaks],
      value = results$smoothed[filtered_peaks]
    )
  } else {
    final_peaks <- NULL
  }

  data_smoothed <- bind_rows(results)

  cat("Processed ID", id, "\n")


  plot_individual <- ggplot(data_smoothed, aes(x = t)) +
    geom_line(aes(y = value, color = "Raw signal"), size = 0.8) +
    geom_line(aes(y = smoothed, color = "Smoothed signal"), size = 0.9) +
    geom_line(aes(y = trend, color = "Trend", linetype = "Trend"), size = 1) +
    geom_point(data = final_valleys, aes(x = time, y = value, color = "Valleys", shape = "Valleys"), size = 2) +
    geom_point(data = final_peaks, aes(x = time, y = value, color = "Peaks", shape = "Peaks"), size = 2) +

    labs(title = paste("Signals and detected peaks - ID", id),
         x = "Time (s)", y = "Intensity", color = "", linetype = "", shape = "") +

    scale_color_manual(values = c(
      "Raw signal" = "gray70",
      "Smoothed signal" = "blue",
      "Trend" = "green",
      "Valleys" = "orange",
      "Peaks" = "red"
    )) +
    scale_linetype_manual(values = c("Trend" = "dashed")) +
    scale_shape_manual(values = c("Valleys" = 16, "Peaks" = 16)) +

    theme_minimal(base_size = 14) +
    theme(
      plot.background = element_rect(fill = "white", color = NA),
      panel.background = element_rect(fill = "white", color = NA),
      strip.background = element_rect(fill = "white", color = NA),
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "black"),
      axis.title = element_text(size = 14, color = "black"),
      axis.text = element_text(size = 12, color = "black"),
      strip.text = element_text(color = "black"),
      legend.text = element_text(color = "black")
    )

  ggsave(filename = file.path(folder_path, "Graphs", paste0("Graph__WATCOLD", id, ".png")),
         plot = plot_individual, width = 12, height = 8, dpi = 300)

  todos_los_resultados_movimiento[[as.character(id)]] <- list(
    data_suavizado = data_smoothed %>% mutate(ID = id),
    valles_finales = final_valleys %>% mutate(ID = id),
    picos_finales = final_peaks %>% mutate(ID = id)
  )
  }

data_suavizado_all <- map_dfr(todos_los_resultados_movimiento, "data_suavizado")
a_1_WATCOLD_valleys <- map_dfr(todos_los_resultados_movimiento, "valles_finales")
picos_WATCOLD_rep <- map_dfr(todos_los_resultados_movimiento, "picos_finales")





ids_disponibles <- 2
todos_los_resultados_movimiento <- list()  # Create an empty list to store results
for (id in ids_disponibles) {
filename <- file.path(folder_path, paste0(id, "_WATCOLD_Ven_Edited.csv"))
    cat("Buscando:", filename, "\n")
  if (!file.exists(filename)) {
    cat("File not found for ID", id, "\n")
    next
  }
  
  data <- read_csv(filename)

duracion_seg <- 60  # o el valor real
data_long <- data %>%   
  select(contains("Mean")) %>% 
  mutate(t = seq(0, duracion_seg, length.out = n())) %>% 
  pivot_longer(-t, names_to = "Mean", values_to = "value")

  results <- data_long %>% arrange(t) %>% 
    mutate(smoothed = sgolayfilt(value, p = 5, n = 25), trend = predict(loess(smoothed ~ t, span = 0.08), newdata = data.frame(t = t))) 

  derivative <- c(NA, diff(results$smoothed))  # Smoothing and derivative
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from negative to positive (local minima)
  valley_indices <- which(significant_changes == 2)
  valley_values <- results$smoothed[valley_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))
  threshold <- 1.02 * trend
  valid_valleys <- valley_indices[valley_values < threshold[valley_indices]]
  min_dist <- 15
  values <- results$smoothed[valid_valleys]
  filtered_valleys <- c()

  if (length(valid_valleys) == 1) {
    filtered_valleys <- valid_valleys
  } else if (length(valid_valleys) > 1) {
    current_group <- c(valid_valleys[1])
    filtered_valleys <- c()
    
    for (i in 2:length(valid_valleys)) {
      if ((valid_valleys[i] - valid_valleys[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_valleys[i])
      } else {
        min_valley <- current_group[which.min(results$smoothed[current_group])]
        filtered_valleys <- c(filtered_valleys, min_valley)
        current_group <- c(valid_valleys[i])
      }
    }
    
    if (length(current_group) > 0) {
      min_valley <- current_group[which.min(results$smoothed[current_group])]
      filtered_valleys <- c(filtered_valleys, min_valley)
    }
  }

  local_valley_threshold <- trend[filtered_valleys]
  filtered_valley_values <- results$smoothed[filtered_valleys]
  valley_trend_filter <- filtered_valley_values < local_valley_threshold
  filtered_valleys <- filtered_valleys[valley_trend_filter]

  if (length(filtered_valleys) > 0) {
    final_valleys <- tibble(
      time = results$t[filtered_valleys],
      value = results$smoothed[filtered_valleys]
    )
  } else {
    final_valleys <- NULL
  }

  derivative <- c(NA, diff(results$smoothed))
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from positive to negative (local maxima)
  peak_indices <- which(significant_changes == -2)
  peak_values <- results$smoothed[peak_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))

  threshold <- 1.01 * trend
  local_threshold <- threshold[peak_indices]

  valid_peaks <- peak_indices[peak_values > local_threshold]
  min_dist <- 18
  values <- results$smoothed[valid_peaks]

  filtered_peaks <- c()

  if (length(valid_peaks) == 1) {
    filtered_peaks <- valid_peaks
  } else if (length(valid_peaks) > 1) {
    current_group <- c(valid_peaks[1])
    filtered_peaks <- c()
    
    for (i in 2:length(valid_peaks)) {
      if ((valid_peaks[i] - valid_peaks[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_peaks[i])
      } else {
        max_peak <- current_group[which.max(results$smoothed[current_group])]
        filtered_peaks <- c(filtered_peaks, max_peak)
        current_group <- c(valid_peaks[i])
      }
    }
    
    if (length(current_group) > 0) {
      max_peak <- current_group[which.max(results$smoothed[current_group])]
      filtered_peaks <- c(filtered_peaks, max_peak)
    }
  }

  local_threshold_filtered <- trend[filtered_peaks]
  filtered_values <- results$smoothed[filtered_peaks]
  trend_filter <- filtered_values > local_threshold_filtered
  filtered_peaks <- filtered_peaks[trend_filter]

  if (length(filtered_peaks) > 0) {
    final_peaks <- tibble(
      time = results$t[filtered_peaks],
      value = results$smoothed[filtered_peaks]
    )
  } else {
    final_peaks <- NULL
  }

  data_smoothed <- bind_rows(results)

  cat("Processed ID", id, "\n")


  plot_individual <- ggplot(data_smoothed, aes(x = t)) +
    geom_line(aes(y = value, color = "Raw signal"), size = 0.8) +
    geom_line(aes(y = smoothed, color = "Smoothed signal"), size = 0.9) +
    geom_line(aes(y = trend, color = "Trend", linetype = "Trend"), size = 1) +
    geom_point(data = final_valleys, aes(x = time, y = value, color = "Valleys", shape = "Valleys"), size = 2) +
    geom_point(data = final_peaks, aes(x = time, y = value, color = "Peaks", shape = "Peaks"), size = 2) +

    labs(title = paste("Signals and detected peaks - ID", id),
         x = "Time (s)", y = "Intensity", color = "", linetype = "", shape = "") +

    scale_color_manual(values = c(
      "Raw signal" = "gray70",
      "Smoothed signal" = "blue",
      "Trend" = "green",
      "Valleys" = "orange",
      "Peaks" = "red"
    )) +
    scale_linetype_manual(values = c("Trend" = "dashed")) +
    scale_shape_manual(values = c("Valleys" = 16, "Peaks" = 16)) +

    theme_minimal(base_size = 14) +
    theme(
      plot.background = element_rect(fill = "white", color = NA),
      panel.background = element_rect(fill = "white", color = NA),
      strip.background = element_rect(fill = "white", color = NA),
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "black"),
      axis.title = element_text(size = 14, color = "black"),
      axis.text = element_text(size = 12, color = "black"),
      strip.text = element_text(color = "black"),
      legend.text = element_text(color = "black")
    )

  ggsave(filename = file.path(folder_path, "Graphs", paste0("Graph__WATCOLD", id, ".png")),
         plot = plot_individual, width = 12, height = 8, dpi = 300)

  todos_los_resultados_movimiento[[as.character(id)]] <- list(
    data_suavizado = data_smoothed %>% mutate(ID = id),
    valles_finales = final_valleys %>% mutate(ID = id),
    picos_finales = final_peaks %>% mutate(ID = id)
  )
  }

data_suavizado_all <- map_dfr(todos_los_resultados_movimiento, "data_suavizado")
a_2_WATCOLD_valleys <- map_dfr(todos_los_resultados_movimiento, "valles_finales")
picos_WATCOLD_rep <- map_dfr(todos_los_resultados_movimiento, "picos_finales")




ids_disponibles <- 3
todos_los_resultados_movimiento <- list()  # Create an empty list to store results
for (id in ids_disponibles) {
filename <- file.path(folder_path, paste0(id, "_WATCOLD_Ven_Edited.csv"))
    cat("Buscando:", filename, "\n")
  if (!file.exists(filename)) {
    cat("File not found for ID", id, "\n")
    next
  }
  
  data <- read_csv(filename)

duracion_seg <- 60  # o el valor real
data_long <- data %>%   
  select(contains("Mean")) %>% 
  mutate(t = seq(0, duracion_seg, length.out = n())) %>% 
  pivot_longer(-t, names_to = "Mean", values_to = "value")

  results <- data_long %>% arrange(t) %>% 
    mutate(smoothed = sgolayfilt(value, p = 5, n = 25), trend = predict(loess(smoothed ~ t, span = 0.04), newdata = data.frame(t = t))) 

  derivative <- c(NA, diff(results$smoothed))  # Smoothing and derivative
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from negative to positive (local minima)
  valley_indices <- which(significant_changes == 2)
  valley_values <- results$smoothed[valley_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.04)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))
  threshold <- 1.05 * trend
  valid_valleys <- valley_indices[valley_values < threshold[valley_indices]]
  min_dist <- 15
  values <- results$smoothed[valid_valleys]
  filtered_valleys <- c()

  if (length(valid_valleys) == 1) {
    filtered_valleys <- valid_valleys
  } else if (length(valid_valleys) > 1) {
    current_group <- c(valid_valleys[1])
    filtered_valleys <- c()
    
    for (i in 2:length(valid_valleys)) {
      if ((valid_valleys[i] - valid_valleys[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_valleys[i])
      } else {
        min_valley <- current_group[which.min(results$smoothed[current_group])]
        filtered_valleys <- c(filtered_valleys, min_valley)
        current_group <- c(valid_valleys[i])
      }
    }
    
    if (length(current_group) > 0) {
      min_valley <- current_group[which.min(results$smoothed[current_group])]
      filtered_valleys <- c(filtered_valleys, min_valley)
    }
  }

  local_valley_threshold <- trend[filtered_valleys]
  filtered_valley_values <- results$smoothed[filtered_valleys]
  valley_trend_filter <- filtered_valley_values < local_valley_threshold
  filtered_valleys <- filtered_valleys[valley_trend_filter]

  if (length(filtered_valleys) > 0) {
    final_valleys <- tibble(
      time = results$t[filtered_valleys],
      value = results$smoothed[filtered_valleys]
    )
  } else {
    final_valleys <- NULL
  }

  derivative <- c(NA, diff(results$smoothed))
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from positive to negative (local maxima)
  peak_indices <- which(significant_changes == -2)
  peak_values <- results$smoothed[peak_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))

  threshold <- 1.01 * trend
  local_threshold <- threshold[peak_indices]

  valid_peaks <- peak_indices[peak_values > local_threshold]
  min_dist <- 18
  values <- results$smoothed[valid_peaks]

  filtered_peaks <- c()

  if (length(valid_peaks) == 1) {
    filtered_peaks <- valid_peaks
  } else if (length(valid_peaks) > 1) {
    current_group <- c(valid_peaks[1])
    filtered_peaks <- c()
    
    for (i in 2:length(valid_peaks)) {
      if ((valid_peaks[i] - valid_peaks[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_peaks[i])
      } else {
        max_peak <- current_group[which.max(results$smoothed[current_group])]
        filtered_peaks <- c(filtered_peaks, max_peak)
        current_group <- c(valid_peaks[i])
      }
    }
    
    if (length(current_group) > 0) {
      max_peak <- current_group[which.max(results$smoothed[current_group])]
      filtered_peaks <- c(filtered_peaks, max_peak)
    }
  }

  local_threshold_filtered <- trend[filtered_peaks]
  filtered_values <- results$smoothed[filtered_peaks]
  trend_filter <- filtered_values > local_threshold_filtered
  filtered_peaks <- filtered_peaks[trend_filter]

  if (length(filtered_peaks) > 0) {
    final_peaks <- tibble(
      time = results$t[filtered_peaks],
      value = results$smoothed[filtered_peaks]
    )
  } else {
    final_peaks <- NULL
  }

  data_smoothed <- bind_rows(results)

  cat("Processed ID", id, "\n")


  plot_individual <- ggplot(data_smoothed, aes(x = t)) +
    geom_line(aes(y = value, color = "Raw signal"), size = 0.8) +
    geom_line(aes(y = smoothed, color = "Smoothed signal"), size = 0.9) +
    geom_line(aes(y = trend, color = "Trend", linetype = "Trend"), size = 1) +
    geom_point(data = final_valleys, aes(x = time, y = value, color = "Valleys", shape = "Valleys"), size = 2) +
    geom_point(data = final_peaks, aes(x = time, y = value, color = "Peaks", shape = "Peaks"), size = 2) +

    labs(title = paste("Signals and detected peaks - ID", id),
         x = "Time (s)", y = "Intensity", color = "", linetype = "", shape = "") +

    scale_color_manual(values = c(
      "Raw signal" = "gray70",
      "Smoothed signal" = "blue",
      "Trend" = "green",
      "Valleys" = "orange",
      "Peaks" = "red"
    )) +
    scale_linetype_manual(values = c("Trend" = "dashed")) +
    scale_shape_manual(values = c("Valleys" = 16, "Peaks" = 16)) +

    theme_minimal(base_size = 14) +
    theme(
      plot.background = element_rect(fill = "white", color = NA),
      panel.background = element_rect(fill = "white", color = NA),
      strip.background = element_rect(fill = "white", color = NA),
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "black"),
      axis.title = element_text(size = 14, color = "black"),
      axis.text = element_text(size = 12, color = "black"),
      strip.text = element_text(color = "black"),
      legend.text = element_text(color = "black")
    )

  ggsave(filename = file.path(folder_path, "Graphs", paste0("Graph__WATCOLD", id, ".png")),
         plot = plot_individual, width = 12, height = 8, dpi = 300)

  todos_los_resultados_movimiento[[as.character(id)]] <- list(
    data_suavizado = data_smoothed %>% mutate(ID = id),
    valles_finales = final_valleys %>% mutate(ID = id),
    picos_finales = final_peaks %>% mutate(ID = id)
  )
  }

data_suavizado_all <- map_dfr(todos_los_resultados_movimiento, "data_suavizado")
a_3_WATCOLD_valleys <- map_dfr(todos_los_resultados_movimiento, "valles_finales")
picos_WATCOLD_rep <- map_dfr(todos_los_resultados_movimiento, "picos_finales")


# Merge all results
all_WATCOLD_valleys <- all_WATCOLD_valleys %>%  bind_rows(a_1_WATCOLD_valleys) %>% bind_rows(a_2_WATCOLD_valleys) %>% bind_rows(a_3_WATCOLD_valleys)

view(all_WATCOLD_valleys)
```

```{r}
#Completado
folder_path <- "C:/Users/jandr/OneDrive - Universidad del rosario/Temperature_Pressure_HRV/Data/data_extraction/Cold_experiment"
Treatments <- c("1°C","8°C","15°C","WATCOLD", "ENVCOLD")
#skipped beat 11, 22, 25.
#Desacartar 5 y 7. 
#Al azar descartar: 8 y 13
ids_disponibles <- c(1, 2, 3, 4, 6, 9,10, 12, 14,15,16,17,18, 19, 20, 21,23,24, 26, 27, 28, 29)
todos_los_resultados_movimiento <- list()  # Create an empty list to store results
for (id in ids_disponibles) {
filename <- file.path(folder_path, paste0(id, "_15°C_Ven_Edited.csv"))
    cat("Buscando:", filename, "\n")
  if (!file.exists(filename)) {
    cat("File not found for ID", id, "\n")
    next
  }
  
  data <- read_csv(filename)

  data_long <- data %>%   
    select(contains("Mean")) %>% mutate(t = seq(0, 60, length.out = n()))%>%
    pivot_longer(-t, names_to = "Mean", values_to = "value") 

  results <- data_long %>% arrange(t) %>% 
    mutate(smoothed = sgolayfilt(value, p = 5, n = 25), trend = predict(loess(smoothed ~ t, span = 0.08), newdata = data.frame(t = t))) 

  derivative <- c(NA, diff(results$smoothed))  # Smoothing and derivative
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from negative to positive (local minima)
  valley_indices <- which(significant_changes == 2)
  valley_values <- results$smoothed[valley_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))
  threshold <- 0.99 * trend
  valid_valleys <- valley_indices[valley_values < threshold[valley_indices]]
  min_dist <- 18
  values <- results$smoothed[valid_valleys]
  filtered_valleys <- c()

  if (length(valid_valleys) == 1) {
    filtered_valleys <- valid_valleys
  } else if (length(valid_valleys) > 1) {
    current_group <- c(valid_valleys[1])
    filtered_valleys <- c()
    
    for (i in 2:length(valid_valleys)) {
      if ((valid_valleys[i] - valid_valleys[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_valleys[i])
      } else {
        min_valley <- current_group[which.min(results$smoothed[current_group])]
        filtered_valleys <- c(filtered_valleys, min_valley)
        current_group <- c(valid_valleys[i])
      }
    }
    
    if (length(current_group) > 0) {
      min_valley <- current_group[which.min(results$smoothed[current_group])]
      filtered_valleys <- c(filtered_valleys, min_valley)
    }
  }

  local_valley_threshold <- trend[filtered_valleys]
  filtered_valley_values <- results$smoothed[filtered_valleys]
  valley_trend_filter <- filtered_valley_values < local_valley_threshold
  filtered_valleys <- filtered_valleys[valley_trend_filter]

  if (length(filtered_valleys) > 0) {
    final_valleys <- tibble(
      time = results$t[filtered_valleys],
      value = results$smoothed[filtered_valleys]
    )
  } else {
    final_valleys <- NULL
  }

  derivative <- c(NA, diff(results$smoothed))
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from positive to negative (local maxima)
  peak_indices <- which(significant_changes == -2)
  peak_values <- results$smoothed[peak_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))

  threshold <- 1.01 * trend
  local_threshold <- threshold[peak_indices]

  valid_peaks <- peak_indices[peak_values > local_threshold]
  min_dist <- 18
  values <- results$smoothed[valid_peaks]

  filtered_peaks <- c()

  if (length(valid_peaks) == 1) {
    filtered_peaks <- valid_peaks
  } else if (length(valid_peaks) > 1) {
    current_group <- c(valid_peaks[1])
    filtered_peaks <- c()
    
    for (i in 2:length(valid_peaks)) {
      if ((valid_peaks[i] - valid_peaks[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_peaks[i])
      } else {
        max_peak <- current_group[which.max(results$smoothed[current_group])]
        filtered_peaks <- c(filtered_peaks, max_peak)
        current_group <- c(valid_peaks[i])
      }
    }
    
    if (length(current_group) > 0) {
      max_peak <- current_group[which.max(results$smoothed[current_group])]
      filtered_peaks <- c(filtered_peaks, max_peak)
    }
  }

  local_threshold_filtered <- trend[filtered_peaks]
  filtered_values <- results$smoothed[filtered_peaks]
  trend_filter <- filtered_values > local_threshold_filtered
  filtered_peaks <- filtered_peaks[trend_filter]

  if (length(filtered_peaks) > 0) {
    final_peaks <- tibble(
      time = results$t[filtered_peaks],
      value = results$smoothed[filtered_peaks]
    )
  } else {
    final_peaks <- NULL
  }

  data_smoothed <- bind_rows(results)

  cat("Processed ID", id, "\n")


  plot_individual <- ggplot(data_smoothed, aes(x = t)) +
    geom_line(aes(y = value, color = "Raw signal"), size = 0.8) +
    geom_line(aes(y = smoothed, color = "Smoothed signal"), size = 0.9) +
    geom_line(aes(y = trend, color = "Trend", linetype = "Trend"), size = 1) +
    geom_point(data = final_valleys, aes(x = time, y = value, color = "Valleys", shape = "Valleys"), size = 2) +
    geom_point(data = final_peaks, aes(x = time, y = value, color = "Peaks", shape = "Peaks"), size = 2) +

    labs(title = paste("Signals and detected peaks - ID", id),
         x = "Time (s)", y = "Intensity", color = "", linetype = "", shape = "") +

    scale_color_manual(values = c(
      "Raw signal" = "gray70",
      "Smoothed signal" = "blue",
      "Trend" = "green",
      "Valleys" = "orange",
      "Peaks" = "red"
    )) +
    scale_linetype_manual(values = c("Trend" = "dashed")) +
    scale_shape_manual(values = c("Valleys" = 16, "Peaks" = 16)) +

    theme_minimal(base_size = 14) +
    theme(
      plot.background = element_rect(fill = "white", color = NA),
      panel.background = element_rect(fill = "white", color = NA),
      strip.background = element_rect(fill = "white", color = NA),
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "black"),
      axis.title = element_text(size = 14, color = "black"),
      axis.text = element_text(size = 12, color = "black"),
      strip.text = element_text(color = "black"),
      legend.text = element_text(color = "black")
    )

  ggsave(filename = file.path(folder_path, "Graphs", paste0("Graph_15°C", id, ".png")),
         plot = plot_individual, width = 12, height = 8, dpi = 300)

  todos_los_resultados_movimiento[[as.character(id)]] <- list(
    data_suavizado = data_smoothed %>% mutate(ID = id),
    valles_finales = final_valleys %>% mutate(ID = id),
    picos_finales = final_peaks %>% mutate(ID = id)
  )
  }

data_suavizado_all <- map_dfr(todos_los_resultados_movimiento, "data_suavizado")
all_15C_valleys <- map_dfr(todos_los_resultados_movimiento, "valles_finales")
picos_15C_rep <- map_dfr(todos_los_resultados_movimiento, "picos_finales")


ids_disponibles <- c(11,22,25)
todos_los_resultados_movimiento <- list()  # Create an empty list to store results
for (id in ids_disponibles) {
filename <- file.path(folder_path, paste0(id, "_15°C_Ven_Edited.csv"))
    cat("Buscando:", filename, "\n")
  if (!file.exists(filename)) {
    cat("File not found for ID", id, "\n")
    next
  }
  
  data <- read_csv(filename)

  data_long <- data %>%   
    select(contains("Mean")) %>% mutate(t = seq(0, 60, length.out = n()))%>%
    pivot_longer(-t, names_to = "Mean", values_to = "value") 

  results <- data_long %>% arrange(t) %>% 
    mutate(smoothed = sgolayfilt(value, p = 5, n = 25), trend = predict(loess(smoothed ~ t, span = 0.08), newdata = data.frame(t = t))) 

  derivative <- c(NA, diff(results$smoothed))  # Smoothing and derivative
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from negative to positive (local minima)
  valley_indices <- which(significant_changes == 2)
  valley_values <- results$smoothed[valley_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))
  threshold <- 1 * trend
  valid_valleys <- valley_indices[valley_values < threshold[valley_indices]]
  min_dist <- 13
  values <- results$smoothed[valid_valleys]
  filtered_valleys <- c()

  if (length(valid_valleys) == 1) {
    filtered_valleys <- valid_valleys
  } else if (length(valid_valleys) > 1) {
    current_group <- c(valid_valleys[1])
    filtered_valleys <- c()
    
    for (i in 2:length(valid_valleys)) {
      if ((valid_valleys[i] - valid_valleys[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_valleys[i])
      } else {
        min_valley <- current_group[which.min(results$smoothed[current_group])]
        filtered_valleys <- c(filtered_valleys, min_valley)
        current_group <- c(valid_valleys[i])
      }
    }
    
    if (length(current_group) > 0) {
      min_valley <- current_group[which.min(results$smoothed[current_group])]
      filtered_valleys <- c(filtered_valleys, min_valley)
    }
  }

  local_valley_threshold <- trend[filtered_valleys]
  filtered_valley_values <- results$smoothed[filtered_valleys]
  valley_trend_filter <- filtered_valley_values < local_valley_threshold
  filtered_valleys <- filtered_valleys[valley_trend_filter]

  if (length(filtered_valleys) > 0) {
    final_valleys <- tibble(
      time = results$t[filtered_valleys],
      value = results$smoothed[filtered_valleys]
    )
  } else {
    final_valleys <- NULL
  }

  derivative <- c(NA, diff(results$smoothed))
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from positive to negative (local maxima)
  peak_indices <- which(significant_changes == -2)
  peak_values <- results$smoothed[peak_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))

  threshold <- 1.01 * trend
  local_threshold <- threshold[peak_indices]

  valid_peaks <- peak_indices[peak_values > local_threshold]
  min_dist <- 18
  values <- results$smoothed[valid_peaks]

  filtered_peaks <- c()

  if (length(valid_peaks) == 1) {
    filtered_peaks <- valid_peaks
  } else if (length(valid_peaks) > 1) {
    current_group <- c(valid_peaks[1])
    filtered_peaks <- c()
    
    for (i in 2:length(valid_peaks)) {
      if ((valid_peaks[i] - valid_peaks[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_peaks[i])
      } else {
        max_peak <- current_group[which.max(results$smoothed[current_group])]
        filtered_peaks <- c(filtered_peaks, max_peak)
        current_group <- c(valid_peaks[i])
      }
    }
    
    if (length(current_group) > 0) {
      max_peak <- current_group[which.max(results$smoothed[current_group])]
      filtered_peaks <- c(filtered_peaks, max_peak)
    }
  }

  local_threshold_filtered <- trend[filtered_peaks]
  filtered_values <- results$smoothed[filtered_peaks]
  trend_filter <- filtered_values > local_threshold_filtered
  filtered_peaks <- filtered_peaks[trend_filter]

  if (length(filtered_peaks) > 0) {
    final_peaks <- tibble(
      time = results$t[filtered_peaks],
      value = results$smoothed[filtered_peaks]
    )
  } else {
    final_peaks <- NULL
  }

  data_smoothed <- bind_rows(results)

  cat("Processed ID", id, "\n")


  plot_individual <- ggplot(data_smoothed, aes(x = t)) +
    geom_line(aes(y = value, color = "Raw signal"), size = 0.8) +
    geom_line(aes(y = smoothed, color = "Smoothed signal"), size = 0.9) +
    geom_line(aes(y = trend, color = "Trend", linetype = "Trend"), size = 1) +
    geom_point(data = final_valleys, aes(x = time, y = value, color = "Valleys", shape = "Valleys"), size = 2) +
    geom_point(data = final_peaks, aes(x = time, y = value, color = "Peaks", shape = "Peaks"), size = 2) +

    labs(title = paste("Signals and detected peaks - ID", id),
         x = "Time (s)", y = "Intensity", color = "", linetype = "", shape = "") +

    scale_color_manual(values = c(
      "Raw signal" = "gray70",
      "Smoothed signal" = "blue",
      "Trend" = "green",
      "Valleys" = "orange",
      "Peaks" = "red"
    )) +
    scale_linetype_manual(values = c("Trend" = "dashed")) +
    scale_shape_manual(values = c("Valleys" = 16, "Peaks" = 16)) +

    theme_minimal(base_size = 14) +
    theme(
      plot.background = element_rect(fill = "white", color = NA),
      panel.background = element_rect(fill = "white", color = NA),
      strip.background = element_rect(fill = "white", color = NA),
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "black"),
      axis.title = element_text(size = 14, color = "black"),
      axis.text = element_text(size = 12, color = "black"),
      strip.text = element_text(color = "black"),
      legend.text = element_text(color = "black")
    )

  ggsave(filename = file.path(folder_path, "Graphs", paste0("Graph_15°C", id, ".png")),
         plot = plot_individual, width = 12, height = 8, dpi = 300)

  todos_los_resultados_movimiento[[as.character(id)]] <- list(
    data_suavizado = data_smoothed %>% mutate(ID = id),
    valles_finales = final_valleys %>% mutate(ID = id),
    picos_finales = final_peaks %>% mutate(ID = id)
  )
  }

data_suavizado_all <- map_dfr(todos_los_resultados_movimiento, "data_suavizado")
a_11_15C_valleys <- map_dfr(todos_los_resultados_movimiento, "valles_finales")
picos_15C_rep <- map_dfr(todos_los_resultados_movimiento, "picos_finales")


# Merge all results
all_15C_valleys <- all_15C_valleys %>% bind_rows(a_11_15C_valleys) 

nrow(unique(all_15C_valleys["ID"]))
view(all_15C_valleys)
```

```{r}
#Completado
folder_path <- "C:/Users/jandr/OneDrive - Universidad del rosario/Temperature_Pressure_HRV/Data/data_extraction/Cold_experiment"
Treatments <- c("1°C","8°C","15°C","WATCOLD", "ENVCOLD")
#Artefacto en 19
#descartar 10 y 24
#Al azar descartar 2 y 19
ids_disponibles <- c(1, 3,4,5, 6, 7, 8, 9,11, 12, 13,14,15,16,17,18, 20, 21,22,23, 25, 26, 27, 28, 29)
todos_los_resultados_movimiento <- list()  # Create an empty list to store results
for (id in ids_disponibles) {
filename <- file.path(folder_path, paste0(id, "_8°C_Ven_Edited.csv"))
    cat("Buscando:", filename, "\n")
  if (!file.exists(filename)) {
    cat("File not found for ID", id, "\n")
    next
  }
  
  data <- read_csv(filename)

  data_long <- data %>%   
    select(contains("Mean")) %>% mutate(t = seq(0, 60, length.out = n()))%>%
    pivot_longer(-t, names_to = "Mean", values_to = "value") 

  results <- data_long %>% arrange(t) %>% 
    mutate(smoothed = sgolayfilt(value, p = 5, n = 25), trend = predict(loess(smoothed ~ t, span = 0.08), newdata = data.frame(t = t))) 

  derivative <- c(NA, diff(results$smoothed))  # Smoothing and derivative
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from negative to positive (local minima)
  valley_indices <- which(significant_changes == 2)
  valley_values <- results$smoothed[valley_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))
  threshold <- 0.99 * trend
  valid_valleys <- valley_indices[valley_values < threshold[valley_indices]]
  min_dist <- 18
  values <- results$smoothed[valid_valleys]
  filtered_valleys <- c()

  if (length(valid_valleys) == 1) {
    filtered_valleys <- valid_valleys
  } else if (length(valid_valleys) > 1) {
    current_group <- c(valid_valleys[1])
    filtered_valleys <- c()
    
    for (i in 2:length(valid_valleys)) {
      if ((valid_valleys[i] - valid_valleys[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_valleys[i])
      } else {
        min_valley <- current_group[which.min(results$smoothed[current_group])]
        filtered_valleys <- c(filtered_valleys, min_valley)
        current_group <- c(valid_valleys[i])
      }
    }
    
    if (length(current_group) > 0) {
      min_valley <- current_group[which.min(results$smoothed[current_group])]
      filtered_valleys <- c(filtered_valleys, min_valley)
    }
  }

  local_valley_threshold <- trend[filtered_valleys]
  filtered_valley_values <- results$smoothed[filtered_valleys]
  valley_trend_filter <- filtered_valley_values < local_valley_threshold
  filtered_valleys <- filtered_valleys[valley_trend_filter]

  if (length(filtered_valleys) > 0) {
    final_valleys <- tibble(
      time = results$t[filtered_valleys],
      value = results$smoothed[filtered_valleys]
    )
  } else {
    final_valleys <- NULL
  }

  derivative <- c(NA, diff(results$smoothed))
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from positive to negative (local maxima)
  peak_indices <- which(significant_changes == -2)
  peak_values <- results$smoothed[peak_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))

  threshold <- 1.01 * trend
  local_threshold <- threshold[peak_indices]

  valid_peaks <- peak_indices[peak_values > local_threshold]
  min_dist <- 18
  values <- results$smoothed[valid_peaks]

  filtered_peaks <- c()

  if (length(valid_peaks) == 1) {
    filtered_peaks <- valid_peaks
  } else if (length(valid_peaks) > 1) {
    current_group <- c(valid_peaks[1])
    filtered_peaks <- c()
    
    for (i in 2:length(valid_peaks)) {
      if ((valid_peaks[i] - valid_peaks[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_peaks[i])
      } else {
        max_peak <- current_group[which.max(results$smoothed[current_group])]
        filtered_peaks <- c(filtered_peaks, max_peak)
        current_group <- c(valid_peaks[i])
      }
    }
    
    if (length(current_group) > 0) {
      max_peak <- current_group[which.max(results$smoothed[current_group])]
      filtered_peaks <- c(filtered_peaks, max_peak)
    }
  }

  local_threshold_filtered <- trend[filtered_peaks]
  filtered_values <- results$smoothed[filtered_peaks]
  trend_filter <- filtered_values > local_threshold_filtered
  filtered_peaks <- filtered_peaks[trend_filter]

  if (length(filtered_peaks) > 0) {
    final_peaks <- tibble(
      time = results$t[filtered_peaks],
      value = results$smoothed[filtered_peaks]
    )
  } else {
    final_peaks <- NULL
  }

  data_smoothed <- bind_rows(results)

  cat("Processed ID", id, "\n")


  plot_individual <- ggplot(data_smoothed, aes(x = t)) +
    geom_line(aes(y = value, color = "Raw signal"), size = 0.8) +
    geom_line(aes(y = smoothed, color = "Smoothed signal"), size = 0.9) +
    geom_line(aes(y = trend, color = "Trend", linetype = "Trend"), size = 1) +
    geom_point(data = final_valleys, aes(x = time, y = value, color = "Valleys", shape = "Valleys"), size = 2) +
    geom_point(data = final_peaks, aes(x = time, y = value, color = "Peaks", shape = "Peaks"), size = 2) +

    labs(title = paste("Signals and detected peaks - ID", id),
         x = "Time (s)", y = "Intensity", color = "", linetype = "", shape = "") +

    scale_color_manual(values = c(
      "Raw signal" = "gray70",
      "Smoothed signal" = "blue",
      "Trend" = "green",
      "Valleys" = "orange",
      "Peaks" = "red"
    )) +
    scale_linetype_manual(values = c("Trend" = "dashed")) +
    scale_shape_manual(values = c("Valleys" = 16, "Peaks" = 16)) +

    theme_minimal(base_size = 14) +
    theme(
      plot.background = element_rect(fill = "white", color = NA),
      panel.background = element_rect(fill = "white", color = NA),
      strip.background = element_rect(fill = "white", color = NA),
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "black"),
      axis.title = element_text(size = 14, color = "black"),
      axis.text = element_text(size = 12, color = "black"),
      strip.text = element_text(color = "black"),
      legend.text = element_text(color = "black")
    )

  ggsave(filename = file.path(folder_path, "Graphs", paste0("Graph_8°C", id, ".png")),
         plot = plot_individual, width = 12, height = 8, dpi = 300)

  todos_los_resultados_movimiento[[as.character(id)]] <- list(
    data_suavizado = data_smoothed %>% mutate(ID = id),
    valles_finales = final_valleys %>% mutate(ID = id),
    picos_finales = final_peaks %>% mutate(ID = id)
  )
  }

data_suavizado_all <- map_dfr(todos_los_resultados_movimiento, "data_suavizado")
all_8C_valleys <- map_dfr(todos_los_resultados_movimiento, "valles_finales")
picos_8C_rep <- map_dfr(todos_los_resultados_movimiento, "picos_finales")

nrow(unique(all_8C_valleys["ID"]))
# Merge all results
View(all_8C_valleys)

```

```{r}
#Completado
folder_path <- "C:/Users/jandr/OneDrive - Universidad del rosario/Temperature_Pressure_HRV/Data/data_extraction/Cold_experiment"
Treatments <- c("1°C","8°C","15°C","WATCOLD", "ENVCOLD")
#arreglado artefacto en 1, 4, 14, 23, 29
#descartar 19, 3, 25 
#al azar descartado: 26
ids_disponibles <- c(1, 2,4, 6, 7, 8, 9,10, 11, 13,15,16,17,18, 20, 21,
                     28, 29)
todos_los_resultados_movimiento <- list()  # Create an empty list to store results
for (id in ids_disponibles) {
filename <- file.path(folder_path, paste0(id, "_1°C_Ven_Edited.csv"))
    cat("Buscando:", filename, "\n")
  if (!file.exists(filename)) {
    cat("File not found for ID", id, "\n")
    next
  }
  
  data <- read_csv(filename)

  data_long <- data %>%   
    select(contains("Mean")) %>% mutate(t = seq(0, 60, length.out = n()))%>%
    pivot_longer(-t, names_to = "Mean", values_to = "value") 

  results <- data_long %>% arrange(t) %>% 
    mutate(smoothed = sgolayfilt(value, p = 5, n = 25), trend = predict(loess(smoothed ~ t, span = 0.08), newdata = data.frame(t = t))) 

  derivative <- c(NA, diff(results$smoothed))  # Smoothing and derivative
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from negative to positive (local minima)
  valley_indices <- which(significant_changes == 2)
  valley_values <- results$smoothed[valley_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))
  threshold <- 0.98 * trend
  valid_valleys <- valley_indices[valley_values < threshold[valley_indices]]
  min_dist <- 18
  values <- results$smoothed[valid_valleys]
  filtered_valleys <- c()

  if (length(valid_valleys) == 1) {
    filtered_valleys <- valid_valleys
  } else if (length(valid_valleys) > 1) {
    current_group <- c(valid_valleys[1])
    filtered_valleys <- c()
    
    for (i in 2:length(valid_valleys)) {
      if ((valid_valleys[i] - valid_valleys[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_valleys[i])
      } else {
        min_valley <- current_group[which.min(results$smoothed[current_group])]
        filtered_valleys <- c(filtered_valleys, min_valley)
        current_group <- c(valid_valleys[i])
      }
    }
    
    if (length(current_group) > 0) {
      min_valley <- current_group[which.min(results$smoothed[current_group])]
      filtered_valleys <- c(filtered_valleys, min_valley)
    }
  }

  local_valley_threshold <- trend[filtered_valleys]
  filtered_valley_values <- results$smoothed[filtered_valleys]
  valley_trend_filter <- filtered_valley_values < local_valley_threshold
  filtered_valleys <- filtered_valleys[valley_trend_filter]

  if (length(filtered_valleys) > 0) {
    final_valleys <- tibble(
      time = results$t[filtered_valleys],
      value = results$smoothed[filtered_valleys]
    )
  } else {
    final_valleys <- NULL
  }

  derivative <- c(NA, diff(results$smoothed))
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from positive to negative (local maxima)
  peak_indices <- which(significant_changes == -2)
  peak_values <- results$smoothed[peak_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))

  threshold <- 1.01 * trend
  local_threshold <- threshold[peak_indices]

  valid_peaks <- peak_indices[peak_values > local_threshold]
  min_dist <- 18
  values <- results$smoothed[valid_peaks]

  filtered_peaks <- c()

  if (length(valid_peaks) == 1) {
    filtered_peaks <- valid_peaks
  } else if (length(valid_peaks) > 1) {
    current_group <- c(valid_peaks[1])
    filtered_peaks <- c()
    
    for (i in 2:length(valid_peaks)) {
      if ((valid_peaks[i] - valid_peaks[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_peaks[i])
      } else {
        max_peak <- current_group[which.max(results$smoothed[current_group])]
        filtered_peaks <- c(filtered_peaks, max_peak)
        current_group <- c(valid_peaks[i])
      }
    }
    
    if (length(current_group) > 0) {
      max_peak <- current_group[which.max(results$smoothed[current_group])]
      filtered_peaks <- c(filtered_peaks, max_peak)
    }
  }

  local_threshold_filtered <- trend[filtered_peaks]
  filtered_values <- results$smoothed[filtered_peaks]
  trend_filter <- filtered_values > local_threshold_filtered
  filtered_peaks <- filtered_peaks[trend_filter]

  if (length(filtered_peaks) > 0) {
    final_peaks <- tibble(
      time = results$t[filtered_peaks],
      value = results$smoothed[filtered_peaks]
    )
  } else {
    final_peaks <- NULL
  }

  data_smoothed <- bind_rows(results)

  cat("Processed ID", id, "\n")


  plot_individual <- ggplot(data_smoothed, aes(x = t)) +
    geom_line(aes(y = value, color = "Raw signal"), size = 0.8) +
    geom_line(aes(y = smoothed, color = "Smoothed signal"), size = 0.9) +
    geom_line(aes(y = trend, color = "Trend", linetype = "Trend"), size = 1) +
    geom_point(data = final_valleys, aes(x = time, y = value, color = "Valleys", shape = "Valleys"), size = 2) +
    geom_point(data = final_peaks, aes(x = time, y = value, color = "Peaks", shape = "Peaks"), size = 2) +

    labs(title = paste("Signals and detected peaks - ID", id),
         x = "Time (s)", y = "Intensity", color = "", linetype = "", shape = "") +

    scale_color_manual(values = c(
      "Raw signal" = "gray70",
      "Smoothed signal" = "blue",
      "Trend" = "green",
      "Valleys" = "orange",
      "Peaks" = "red"
    )) +
    scale_linetype_manual(values = c("Trend" = "dashed")) +
    scale_shape_manual(values = c("Valleys" = 16, "Peaks" = 16)) +

    theme_minimal(base_size = 14) +
    theme(
      plot.background = element_rect(fill = "white", color = NA),
      panel.background = element_rect(fill = "white", color = NA),
      strip.background = element_rect(fill = "white", color = NA),
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "black"),
      axis.title = element_text(size = 14, color = "black"),
      axis.text = element_text(size = 12, color = "black"),
      strip.text = element_text(color = "black"),
      legend.text = element_text(color = "black")
    )

  ggsave(filename = file.path(folder_path, "Graphs", paste0("Graph_1.5°C", id, ".png")),
         plot = plot_individual, width = 12, height = 8, dpi = 300)

  todos_los_resultados_movimiento[[as.character(id)]] <- list(
    data_suavizado = data_smoothed %>% mutate(ID = id),
    valles_finales = final_valleys %>% mutate(ID = id),
    picos_finales = final_peaks %>% mutate(ID = id)
  )
  }

data_suavizado_all <- map_dfr(todos_los_resultados_movimiento, "data_suavizado")
all_1C_valleys <- map_dfr(todos_los_resultados_movimiento, "valles_finales")
picos_1C_rep <- map_dfr(todos_los_resultados_movimiento, "picos_finales")

ids_disponibles <- c(5, 12, 22, 24)
todos_los_resultados_movimiento <- list()  # Create an empty list to store results
for (id in ids_disponibles) {
filename <- file.path(folder_path, paste0(id, "_1°C_Ven_Edited.csv"))
    cat("Buscando:", filename, "\n")
  if (!file.exists(filename)) {
    cat("File not found for ID", id, "\n")
    next
  }
  
  data <- read_csv(filename)

  data_long <- data %>%   
    select(contains("Mean")) %>% mutate(t = seq(0, 60, length.out = n()))%>%
    pivot_longer(-t, names_to = "Mean", values_to = "value") 

  results <- data_long %>% arrange(t) %>% 
    mutate(smoothed = sgolayfilt(value, p = 5, n = 25), trend = predict(loess(smoothed ~ t, span = 0.08), newdata = data.frame(t = t))) 

  derivative <- c(NA, diff(results$smoothed))  # Smoothing and derivative
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from negative to positive (local minima)
  valley_indices <- which(significant_changes == 2)
  valley_values <- results$smoothed[valley_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))
  threshold <- 0.99 * trend
  valid_valleys <- valley_indices[valley_values < threshold[valley_indices]]
  min_dist <- 18
  values <- results$smoothed[valid_valleys]
  filtered_valleys <- c()

  if (length(valid_valleys) == 1) {
    filtered_valleys <- valid_valleys
  } else if (length(valid_valleys) > 1) {
    current_group <- c(valid_valleys[1])
    filtered_valleys <- c()
    
    for (i in 2:length(valid_valleys)) {
      if ((valid_valleys[i] - valid_valleys[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_valleys[i])
      } else {
        min_valley <- current_group[which.min(results$smoothed[current_group])]
        filtered_valleys <- c(filtered_valleys, min_valley)
        current_group <- c(valid_valleys[i])
      }
    }
    
    if (length(current_group) > 0) {
      min_valley <- current_group[which.min(results$smoothed[current_group])]
      filtered_valleys <- c(filtered_valleys, min_valley)
    }
  }

  local_valley_threshold <- trend[filtered_valleys]
  filtered_valley_values <- results$smoothed[filtered_valleys]
  valley_trend_filter <- filtered_valley_values < local_valley_threshold
  filtered_valleys <- filtered_valleys[valley_trend_filter]

  if (length(filtered_valleys) > 0) {
    final_valleys <- tibble(
      time = results$t[filtered_valleys],
      value = results$smoothed[filtered_valleys]
    )
  } else {
    final_valleys <- NULL
  }

  derivative <- c(NA, diff(results$smoothed))
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from positive to negative (local maxima)
  peak_indices <- which(significant_changes == -2)
  peak_values <- results$smoothed[peak_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))

  threshold <- 1.01 * trend
  local_threshold <- threshold[peak_indices]

  valid_peaks <- peak_indices[peak_values > local_threshold]
  min_dist <- 18
  values <- results$smoothed[valid_peaks]

  filtered_peaks <- c()

  if (length(valid_peaks) == 1) {
    filtered_peaks <- valid_peaks
  } else if (length(valid_peaks) > 1) {
    current_group <- c(valid_peaks[1])
    filtered_peaks <- c()
    
    for (i in 2:length(valid_peaks)) {
      if ((valid_peaks[i] - valid_peaks[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_peaks[i])
      } else {
        max_peak <- current_group[which.max(results$smoothed[current_group])]
        filtered_peaks <- c(filtered_peaks, max_peak)
        current_group <- c(valid_peaks[i])
      }
    }
    
    if (length(current_group) > 0) {
      max_peak <- current_group[which.max(results$smoothed[current_group])]
      filtered_peaks <- c(filtered_peaks, max_peak)
    }
  }

  local_threshold_filtered <- trend[filtered_peaks]
  filtered_values <- results$smoothed[filtered_peaks]
  trend_filter <- filtered_values > local_threshold_filtered
  filtered_peaks <- filtered_peaks[trend_filter]

  if (length(filtered_peaks) > 0) {
    final_peaks <- tibble(
      time = results$t[filtered_peaks],
      value = results$smoothed[filtered_peaks]
    )
  } else {
    final_peaks <- NULL
  }

  data_smoothed <- bind_rows(results)

  cat("Processed ID", id, "\n")


  plot_individual <- ggplot(data_smoothed, aes(x = t)) +
    geom_line(aes(y = value, color = "Raw signal"), size = 0.8) +
    geom_line(aes(y = smoothed, color = "Smoothed signal"), size = 0.9) +
    geom_line(aes(y = trend, color = "Trend", linetype = "Trend"), size = 1) +
    geom_point(data = final_valleys, aes(x = time, y = value, color = "Valleys", shape = "Valleys"), size = 2) +
    geom_point(data = final_peaks, aes(x = time, y = value, color = "Peaks", shape = "Peaks"), size = 2) +

    labs(title = paste("Signals and detected peaks - ID", id),
         x = "Time (s)", y = "Intensity", color = "", linetype = "", shape = "") +

    scale_color_manual(values = c(
      "Raw signal" = "gray70",
      "Smoothed signal" = "blue",
      "Trend" = "green",
      "Valleys" = "orange",
      "Peaks" = "red"
    )) +
    scale_linetype_manual(values = c("Trend" = "dashed")) +
    scale_shape_manual(values = c("Valleys" = 16, "Peaks" = 16)) +

    theme_minimal(base_size = 14) +
    theme(
      plot.background = element_rect(fill = "white", color = NA),
      panel.background = element_rect(fill = "white", color = NA),
      strip.background = element_rect(fill = "white", color = NA),
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "black"),
      axis.title = element_text(size = 14, color = "black"),
      axis.text = element_text(size = 12, color = "black"),
      strip.text = element_text(color = "black"),
      legend.text = element_text(color = "black")
    )

  ggsave(filename = file.path(folder_path, "Graphs", paste0("Graph_1.5°C", id, ".png")),
         plot = plot_individual, width = 12, height = 8, dpi = 300)

  todos_los_resultados_movimiento[[as.character(id)]] <- list(
    data_suavizado = data_smoothed %>% mutate(ID = id),
    valles_finales = final_valleys %>% mutate(ID = id),
    picos_finales = final_peaks %>% mutate(ID = id)
  )
  }

data_suavizado_all <- map_dfr(todos_los_resultados_movimiento, "data_suavizado")
a_5_1C_valleys <- map_dfr(todos_los_resultados_movimiento, "valles_finales")
picos_1C_rep <- map_dfr(todos_los_resultados_movimiento, "picos_finales")


ids_disponibles <- c(14,27)
todos_los_resultados_movimiento <- list()  # Create an empty list to store results
for (id in ids_disponibles) {
filename <- file.path(folder_path, paste0(id, "_1°C_Ven_Edited.csv"))
    cat("Buscando:", filename, "\n")
  if (!file.exists(filename)) {
    cat("File not found for ID", id, "\n")
    next
  }
  
  data <- read_csv(filename)

  data_long <- data %>%   
    select(contains("Mean")) %>% mutate(t = seq(0, 60, length.out = n()))%>%
    pivot_longer(-t, names_to = "Mean", values_to = "value") 

  results <- data_long %>% arrange(t) %>% 
    mutate(smoothed = sgolayfilt(value, p = 5, n = 25), trend = predict(loess(smoothed ~ t, span = 0.12), newdata = data.frame(t = t))) 

  derivative <- c(NA, diff(results$smoothed))  # Smoothing and derivative
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from negative to positive (local minima)
  valley_indices <- which(significant_changes == 2)
  valley_values <- results$smoothed[valley_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.12)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))
  threshold <- 0.98 * trend
  valid_valleys <- valley_indices[valley_values < threshold[valley_indices]]
  min_dist <- 25
  values <- results$smoothed[valid_valleys]
  filtered_valleys <- c()

  if (length(valid_valleys) == 1) {
    filtered_valleys <- valid_valleys
  } else if (length(valid_valleys) > 1) {
    current_group <- c(valid_valleys[1])
    filtered_valleys <- c()
    
    for (i in 2:length(valid_valleys)) {
      if ((valid_valleys[i] - valid_valleys[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_valleys[i])
      } else {
        min_valley <- current_group[which.min(results$smoothed[current_group])]
        filtered_valleys <- c(filtered_valleys, min_valley)
        current_group <- c(valid_valleys[i])
      }
    }
    
    if (length(current_group) > 0) {
      min_valley <- current_group[which.min(results$smoothed[current_group])]
      filtered_valleys <- c(filtered_valleys, min_valley)
    }
  }

  local_valley_threshold <- trend[filtered_valleys]
  filtered_valley_values <- results$smoothed[filtered_valleys]
  valley_trend_filter <- filtered_valley_values < local_valley_threshold
  filtered_valleys <- filtered_valleys[valley_trend_filter]

  if (length(filtered_valleys) > 0) {
    final_valleys <- tibble(
      time = results$t[filtered_valleys],
      value = results$smoothed[filtered_valleys]
    )
  } else {
    final_valleys <- NULL
  }

  derivative <- c(NA, diff(results$smoothed))
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from positive to negative (local maxima)
  peak_indices <- which(significant_changes == -2)
  peak_values <- results$smoothed[peak_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))

  threshold <- 1.01 * trend
  local_threshold <- threshold[peak_indices]

  valid_peaks <- peak_indices[peak_values > local_threshold]
  min_dist <- 18
  values <- results$smoothed[valid_peaks]

  filtered_peaks <- c()

  if (length(valid_peaks) == 1) {
    filtered_peaks <- valid_peaks
  } else if (length(valid_peaks) > 1) {
    current_group <- c(valid_peaks[1])
    filtered_peaks <- c()
    
    for (i in 2:length(valid_peaks)) {
      if ((valid_peaks[i] - valid_peaks[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_peaks[i])
      } else {
        max_peak <- current_group[which.max(results$smoothed[current_group])]
        filtered_peaks <- c(filtered_peaks, max_peak)
        current_group <- c(valid_peaks[i])
      }
    }
    
    if (length(current_group) > 0) {
      max_peak <- current_group[which.max(results$smoothed[current_group])]
      filtered_peaks <- c(filtered_peaks, max_peak)
    }
  }

  local_threshold_filtered <- trend[filtered_peaks]
  filtered_values <- results$smoothed[filtered_peaks]
  trend_filter <- filtered_values > local_threshold_filtered
  filtered_peaks <- filtered_peaks[trend_filter]

  if (length(filtered_peaks) > 0) {
    final_peaks <- tibble(
      time = results$t[filtered_peaks],
      value = results$smoothed[filtered_peaks]
    )
  } else {
    final_peaks <- NULL
  }

  data_smoothed <- bind_rows(results)

  cat("Processed ID", id, "\n")


  plot_individual <- ggplot(data_smoothed, aes(x = t)) +
    geom_line(aes(y = value, color = "Raw signal"), size = 0.8) +
    geom_line(aes(y = smoothed, color = "Smoothed signal"), size = 0.9) +
    geom_line(aes(y = trend, color = "Trend", linetype = "Trend"), size = 1) +
    geom_point(data = final_valleys, aes(x = time, y = value, color = "Valleys", shape = "Valleys"), size = 2) +
    geom_point(data = final_peaks, aes(x = time, y = value, color = "Peaks", shape = "Peaks"), size = 2) +

    labs(title = paste("Signals and detected peaks - ID", id),
         x = "Time (s)", y = "Intensity", color = "", linetype = "", shape = "") +

    scale_color_manual(values = c(
      "Raw signal" = "gray70",
      "Smoothed signal" = "blue",
      "Trend" = "green",
      "Valleys" = "orange",
      "Peaks" = "red"
    )) +
    scale_linetype_manual(values = c("Trend" = "dashed")) +
    scale_shape_manual(values = c("Valleys" = 16, "Peaks" = 16)) +

    theme_minimal(base_size = 14) +
    theme(
      plot.background = element_rect(fill = "white", color = NA),
      panel.background = element_rect(fill = "white", color = NA),
      strip.background = element_rect(fill = "white", color = NA),
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "black"),
      axis.title = element_text(size = 14, color = "black"),
      axis.text = element_text(size = 12, color = "black"),
      strip.text = element_text(color = "black"),
      legend.text = element_text(color = "black")
    )

  ggsave(filename = file.path(folder_path, "Graphs", paste0("Graph_1.5°C", id, ".png")),
         plot = plot_individual, width = 12, height = 8, dpi = 300)

  todos_los_resultados_movimiento[[as.character(id)]] <- list(
    data_suavizado = data_smoothed %>% mutate(ID = id),
    valles_finales = final_valleys %>% mutate(ID = id),
    picos_finales = final_peaks %>% mutate(ID = id)
  )
  }

data_suavizado_all <- map_dfr(todos_los_resultados_movimiento, "data_suavizado")
a_14_1C_valleys <- map_dfr(todos_los_resultados_movimiento, "valles_finales")
picos_1C_rep <- map_dfr(todos_los_resultados_movimiento, "picos_finales")


ids_disponibles <- 23
todos_los_resultados_movimiento <- list()  # Create an empty list to store results
for (id in ids_disponibles) {
filename <- file.path(folder_path, paste0(id, "_1°C_Ven_Edited.csv"))
    cat("Buscando:", filename, "\n")
  if (!file.exists(filename)) {
    cat("File not found for ID", id, "\n")
    next
  }
  
  data <- read_csv(filename)

  data_long <- data %>%   
    select(contains("Mean")) %>% mutate(t = seq(0, 60, length.out = n()))%>%
    pivot_longer(-t, names_to = "Mean", values_to = "value") 

  results <- data_long %>% arrange(t) %>% 
    mutate(smoothed = sgolayfilt(value, p = 5, n = 25), trend = predict(loess(smoothed ~ t, span = 0.12), newdata = data.frame(t = t))) 

  derivative <- c(NA, diff(results$smoothed))  # Smoothing and derivative
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from negative to positive (local minima)
  valley_indices <- which(significant_changes == 2)
  valley_values <- results$smoothed[valley_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.12)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))
  threshold <- 0.99 * trend
  valid_valleys <- valley_indices[valley_values < threshold[valley_indices]]
  min_dist <- 23
  values <- results$smoothed[valid_valleys]
  filtered_valleys <- c()

  if (length(valid_valleys) == 1) {
    filtered_valleys <- valid_valleys
  } else if (length(valid_valleys) > 1) {
    current_group <- c(valid_valleys[1])
    filtered_valleys <- c()
    
    for (i in 2:length(valid_valleys)) {
      if ((valid_valleys[i] - valid_valleys[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_valleys[i])
      } else {
        min_valley <- current_group[which.min(results$smoothed[current_group])]
        filtered_valleys <- c(filtered_valleys, min_valley)
        current_group <- c(valid_valleys[i])
      }
    }
    
    if (length(current_group) > 0) {
      min_valley <- current_group[which.min(results$smoothed[current_group])]
      filtered_valleys <- c(filtered_valleys, min_valley)
    }
  }

  local_valley_threshold <- trend[filtered_valleys]
  filtered_valley_values <- results$smoothed[filtered_valleys]
  valley_trend_filter <- filtered_valley_values < local_valley_threshold
  filtered_valleys <- filtered_valleys[valley_trend_filter]

  if (length(filtered_valleys) > 0) {
    final_valleys <- tibble(
      time = results$t[filtered_valleys],
      value = results$smoothed[filtered_valleys]
    )
  } else {
    final_valleys <- NULL
  }

  derivative <- c(NA, diff(results$smoothed))
  changes <- sign(derivative)
  significant_changes <- c(NA, diff(changes))

  # Indices where it changes from positive to negative (local maxima)
  peak_indices <- which(significant_changes == -2)
  peak_values <- results$smoothed[peak_indices]

  trend_fit <- loess(smoothed ~ t, data = results, span = 0.08)
  trend <- predict(trend_fit, newdata = data.frame(t = results$t))

  threshold <- 1.01 * trend
  local_threshold <- threshold[peak_indices]

  valid_peaks <- peak_indices[peak_values > local_threshold]
  min_dist <- 18
  values <- results$smoothed[valid_peaks]

  filtered_peaks <- c()

  if (length(valid_peaks) == 1) {
    filtered_peaks <- valid_peaks
  } else if (length(valid_peaks) > 1) {
    current_group <- c(valid_peaks[1])
    filtered_peaks <- c()
    
    for (i in 2:length(valid_peaks)) {
      if ((valid_peaks[i] - valid_peaks[i - 1]) <= min_dist) {
        current_group <- c(current_group, valid_peaks[i])
      } else {
        max_peak <- current_group[which.max(results$smoothed[current_group])]
        filtered_peaks <- c(filtered_peaks, max_peak)
        current_group <- c(valid_peaks[i])
      }
    }
    
    if (length(current_group) > 0) {
      max_peak <- current_group[which.max(results$smoothed[current_group])]
      filtered_peaks <- c(filtered_peaks, max_peak)
    }
  }

  local_threshold_filtered <- trend[filtered_peaks]
  filtered_values <- results$smoothed[filtered_peaks]
  trend_filter <- filtered_values > local_threshold_filtered
  filtered_peaks <- filtered_peaks[trend_filter]

  if (length(filtered_peaks) > 0) {
    final_peaks <- tibble(
      time = results$t[filtered_peaks],
      value = results$smoothed[filtered_peaks]
    )
  } else {
    final_peaks <- NULL
  }

  data_smoothed <- bind_rows(results)

  cat("Processed ID", id, "\n")


  plot_individual <- ggplot(data_smoothed, aes(x = t)) +
    geom_line(aes(y = value, color = "Raw signal"), size = 0.8) +
    geom_line(aes(y = smoothed, color = "Smoothed signal"), size = 0.9) +
    geom_line(aes(y = trend, color = "Trend", linetype = "Trend"), size = 1) +
    geom_point(data = final_valleys, aes(x = time, y = value, color = "Valleys", shape = "Valleys"), size = 2) +
    geom_point(data = final_peaks, aes(x = time, y = value, color = "Peaks", shape = "Peaks"), size = 2) +

    labs(title = paste("Signals and detected peaks - ID", id),
         x = "Time (s)", y = "Intensity", color = "", linetype = "", shape = "") +

    scale_color_manual(values = c(
      "Raw signal" = "gray70",
      "Smoothed signal" = "blue",
      "Trend" = "green",
      "Valleys" = "orange",
      "Peaks" = "red"
    )) +
    scale_linetype_manual(values = c("Trend" = "dashed")) +
    scale_shape_manual(values = c("Valleys" = 16, "Peaks" = 16)) +

    theme_minimal(base_size = 14) +
    theme(
      plot.background = element_rect(fill = "white", color = NA),
      panel.background = element_rect(fill = "white", color = NA),
      strip.background = element_rect(fill = "white", color = NA),
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "black"),
      axis.title = element_text(size = 14, color = "black"),
      axis.text = element_text(size = 12, color = "black"),
      strip.text = element_text(color = "black"),
      legend.text = element_text(color = "black")
    )

  ggsave(filename = file.path(folder_path, "Graphs", paste0("Graph_1.5°C", id, ".png")),
         plot = plot_individual, width = 12, height = 8, dpi = 300)

  todos_los_resultados_movimiento[[as.character(id)]] <- list(
    data_suavizado = data_smoothed %>% mutate(ID = id),
    valles_finales = final_valleys %>% mutate(ID = id),
    picos_finales = final_peaks %>% mutate(ID = id)
  )
  }

data_suavizado_all <- map_dfr(todos_los_resultados_movimiento, "data_suavizado")
a_23_1C_valleys <- map_dfr(todos_los_resultados_movimiento, "valles_finales")
picos_1C_rep <- map_dfr(todos_los_resultados_movimiento, "picos_finales")

all_1C_valleys <- all_1C_valleys %>%  bind_rows(a_5_1C_valleys) %>%  bind_rows(a_14_1C_valleys) %>% bind_rows(a_23_1C_valleys)

nrow(unique(all_1C_valleys["ID"]))
view(all_1C_valleys)
```

```{r}

all_ENVCOLD_valleys <- all_ENVCOLD_valleys %>% 
  mutate(estado = "ENVCOLD")

all_WATCOLD_valleys <- all_WATCOLD_valleys %>% 
  mutate(estado = "WATCOLD")
all_15C_valleys <- all_15C_valleys %>% 
  mutate(estado = "15C")
all_8C_valleys <- all_8C_valleys %>% 
  mutate(estado = "8C")
all_1C_valleys <- all_1C_valleys %>% 
  mutate(estado = "1C")

all_valleys_complete_cold <- bind_rows(all_ENVCOLD_valleys, all_WATCOLD_valleys, all_15C_valleys, all_8C_valleys, all_1C_valleys)

view(all_valleys_complete_cold)

extract_metrics_snail_mov <- function(hrv_obj, id) {
  if (!is.null(hrv_obj$TimeAnalysis[[1]])) {
    ta <- hrv_obj$TimeAnalysis[[1]] 
    RR_ms <- hrv_obj$Beat 
    data.frame(
      ID = id,
      MeanHR_mov = mean(hrv_obj$HR, na.rm = TRUE),
      SDNN_mov = ta$SDNN,
      RMSSD_mov = ta$rMSSD,
      pNN50_mov = ta$pNN50,
      NNi_mov = mean(RR_ms$RR),
      stringsAsFactors = FALSE
    )
  } else {
    data.frame(
      ID = id,
      MeanHR_mov = NA,
      LF_mov = NA,
      HF_mov = NA,
      LFHF_mov = NA,
      SDNN_mov = NA,
      RMSSD_mov = NA,
      pNN50_mov = NA,
      NNi_mov = NA,
      stringsAsFactors = FALSE
    )
  }
}

grouped <- all_valleys_complete_cold %>% group_by(estado, ID)
data_by_snail_mov <- grouped %>% group_split()
Real_IDs <- grouped %>% group_keys() 
results_HRV_mov<- lapply(data_by_snail_mov, function(df_snail) {
  HRV <- CreateHRVData()
  HRV <- LoadBeatVector(HRV, df_snail$time)
  HRV <- BuildNIHR(HRV)
  HRV <- InterpolateNIHR(HRV)
  HRV <- CreateTimeAnalysis(HRV, size = 80, interval = 7.8125)
  return(HRV)
})

names(results_HRV_mov) <- names(results_HRV_mov) <- paste0(Real_IDs$estado, "_", Real_IDs$ID)
HRV_metrics_cold<- imap_dfr(results_HRV_mov, ~ extract_metrics_snail_mov(.x, .y))

HRV_metrics_cold <- HRV_metrics_cold %>%
  tidyr::separate(ID, into = c("Treatment", "Snail"), sep = "_")

view(HRV_metrics_cold)

HRV_metrics_total <- bind_rows(Cold = HRV_metrics_cold, Heat = HRV_metrics_Heat, .id = "Block")
View(HRV_metrics_total)

write_csv(HRV_metrics_total, "C:/Users/jandr/OneDrive - Universidad del rosario/Temperature_Pressure_HRV/Data/data_extraction/HRV_metrics_total_T_exp.csv")

ggplot(data =HRV_metrics_mov, aes(x= Treatment, y= MeanHR_mov))+ geom_violin( color = "grey60", linewidth = 0.3, alpha = 0.1)  + geom_boxplot(width = 0.2, outlier.shape = NA, alpha = 1,size =0.2)+ geom_point() + theme_bw() + ggtitle("Experimento baja temperatura") + xlab("Tratamiento") + ylab("Frecuencia cardiaca (BPM)") + annotate("text", x = 2, y = 100, label = "ENVCOLD: Afuera del agua T ambiente", size = 3.5, color = "steelblue4", fontface = "italic") + annotate("text", x = 2, y = 95, label = "WATCOLD: Después de agua a T ambiente", size = 3.5, color = "steelblue4", fontface = "italic") + annotate("text", x = 2, y = 90, label = " p-value = 2.459e-10 ", size = 3.5, color = "steelblue4", fontface = "italic") + stat_summary(fun = mean, geom = "point", shape = 21, fill = "red", color = "black", size = 1.5) 

HRV_metrics_mov <- HRV_metrics_mov %>% mutate(Experiment="Cold")


kruskal.test(MeanHR_mov ~ ID, data = HRV_metrics_mov)

library("FSA")  # o 'dunn.test' si prefieres
dunnTest(MeanHR_mov ~ ID, data = HRV_metrics_mov, method = "bonferroni")
```

```{r}



library(dplyr)
all_valleys_complete
HR_data <- all_valleys_complete %>%
  group_by(ID, estado) %>%
  arrange(time) %>%
  mutate(
    delta_t = time - lag(time),
    HR = 60 / delta_t  # HR instantánea entre latidos consecutivos
  ) %>%
  dplyr::filter(!is.na(HR)) %>%
  mutate(period = ifelse(time <= 30, "First_30s", "Last_30s")) %>%
  group_by(ID, estado, period) %>%
  summarise(mean_HR = mean(HR, na.rm = TRUE), .groups = "drop")

library(ggplot2)

ggplot(HR_data, aes(x = period, y = mean_HR, color = estado)) +
  geom_boxplot(alpha = 0.3, outlier.shape = NA) +
  geom_point(aes(group = ID), position = position_jitter(width = 0.1)) +
  geom_line(aes(group = ID), alpha = 0.3) +
  facet_wrap(~estado, scales = "free_y") +
  labs(x = "Periodo", y = "Frecuencia cardiaca media (bpm)") +
  theme_minimal()

stats_results <- HR_data %>%
  group_by(estado) %>%
  t_test(mean_HR ~ period, paired = TRUE) %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj")

view(stats_results)
```


